---

apiVersion: batch/v1
kind: Job
metadata:
  name: curator
spec:
  template:
    spec:
      containers:
        - name: curator
          image: bobrik/curator:5.0.1
          args: ["--config", "/etc/config/config.yml", "/etc/config/action_file.yml"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: curator-config
      restartPolicy: OnFailure
